### ISSUE TITLE
package for npm

### ISSUE THREAD

**Issue by shackbarth** [neodon/react-multiselect#1]
This project can't be accessed through a typical npm/browserify workflow because this line:

https://github.com/neodon/react-multiselect/blob/2734b1b8587bca407e889aae25fdba1a326eedae/package.json#L26

points to a file that does exist. Just point it to the file you're exporting your component from, and it should work.

**Comment by shackbarth** [comment]
Then you'll have to `npm publish`, of couse.

**Comment by neodon** [comment]
Thank you for reporting this.  I'll take a look and get it fixed.

**Comment by neodon** [comment]
Sorry for the long delay.  I think I was able to fix the issue as well as a problem preventing the react dependencies from being installed when the module is installed.  Would you mind seeing if you are able to get it to work with the latest version?  Do you still use this module?

**Comment by shackbarth** [comment]
Thanks for fixing and publishing it. I ended up going for https://github.com/JedWatson/react-select instead. But I *did* take your package for a test drive and confirmed that I could now `npm install` it.
